version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: npm
    ports:
      - '80:80'
      - '443:443'
      # '81:81'
    environment:
        DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      # ./websites:/mnt/user/appdata/NginxProxyManager/websites

networks:
  default:
    external: true
    name: npm-proxy


#Note enable TLS as full when using cloudflare SSL certs 