version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
#    user: 1000:1000 # should be owner of volumes
#    ports:
#     - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
    networks:
      - npm-proxy

networks:
  default:
    external: true
    name: npm-proxy

# user PUID and PGID is commented out as docker is running on root user